const Map<String, String> enUS = {
  'app_title': 'haha POS',
  'welcome': 'Welcome',
  'let_start_now': 'Let\'s start now!',
  'sign_in': 'Sign In',
  'sign_out': 'Sign Out',
  'register_device': 'Register Device',
  'unregister_device': 'Unregister Device',
  'register_user': 'Register User',
  'unregister_user': 'Unregister User',
  'register_institution': 'Register Corporate',
  'unregister_institution': 'Unregister Corporate',
  'power_by': 'Power by Batix',
  'user_id': 'User ID',
  'user_id_placeholder': 'Enter User ID',
  'user_id_is_required': 'User ID is required',
  'user_id_min_max_validation': 'User ID should be 5~15 characters',
  'password': 'Password',
  'password_placeholder': 'Enter Password',
  'password_is_required': 'Password is required',
  'password_min_max_validation': 'Password should be 5~15 characters',
  'confirm_password': 'Confirm Password',
  'confirm_password_placeholder': 'Enter Confirm Password',
  'confirm_password_is_required': 'Confirm Password is required',
  'confirm_password_not_consistence':
      'Confirm Password is not consistence with Password.',
  'phone': 'Phone Number',
  'phone_placeholder': 'Enter Phone Number',
  'phone_is_required': 'Phone Number is required',
  'phone_min_max_validation': 'Phone  Numbershould be 6~15 characters',
  'name': 'Name',
  'name_placeholder': 'Enter Name',
  'name_is_required': 'Name is required',
  'name_min_max_validation': 'Name should be 3~50 characters',
  'privacy_policy': 'Privacy & Policy',
  'aggree_with_term_policy':
      'I have read and agreed to the Tehaha & Conditions and Privay Policy of Batix.',
  'home': 'Home',
  'sell': 'Sell',
  'buy': 'Buy',
  'me': 'Me',
  'setting': 'Setting',
  'inbox': 'Inbox',
  'change_password': 'Change Password',
  'change_language': 'Change Language',
  'change_theme': 'Change Theme',
  'contact': 'Contact',
  'help': 'Help',
  'about': 'About',
  'more': 'More',
  'total_sell': 'Total Selling',
  'open_order': 'Open Order',
  'close_order': 'Close Order',
  'cash': 'Cash',
  'debit_card': 'Debit Card',
  'credit_card': 'Credit Card',
  'transfer': 'Transfer',
  'send_a_message': 'Send a message',
  'item': 'Item',
  'properties': 'Property',
  'billings': 'Billing',
  'transactions': 'Transactions',
  'informal': 'Street Vendor',
  'household': 'Residential Home',
  'transportation': 'Transportation',
  'social': 'Social',
  'public': 'Public Place',
  'open': 'Not Paid',
  'close': 'Paid',
  'cancel': 'Canceled',
  'amnesty': 'Amnesty',
  'market-close': 'Market Close',
  'booth-close': 'Booth Close',
  'booth-refuse': 'Booth Refuse To Pay',
};
