const Map<String, String> inID = {
  'app_title': 'haha POS',
  'welcome': 'Selamat Datang',
  'let_start_now': 'Ayo Mulai Sekarang!',
  'sign_in': 'Sign In',
  'sign_out': 'Sign Out',
  'register_device': 'Daftarkan Perangkat',
  'unregister_device': 'Unregister Perangkat',
  'register_user': 'Daftarkan Pengguna',
  'unregister_user': 'Unregister Pengguna',
  'register_institution': 'Daftarkan Perusahaan',
  'unregister_institution': 'Unregister Perusahaan',
  'power_by': 'Power by Batix',
  'user_id': 'ID Pengguna',
  'user_id_placeholder': 'Masukan ID Pengguna',
  'user_id_is_required': 'ID Pengguna harus diisi',
  'user_id_min_max_validation': 'ID Pengguna harus 5~15 karakter',
  'password': 'Kata Sandi',
  'password_placeholder': 'Masukan Kata Sandi',
  'password_is_required': 'Kata Sandi harus diisi',
  'password_min_max_validation': 'Kata Sandi harus 5~15 karakter',
  'confirm_password': 'Konfirmasi Kata Sandi',
  'confirm_password_placeholder': 'Masukan Konfirmasi Kata Sandi',
  'confirm_password_is_required': 'Konfirmasi Kata Sandi harus diisi',
  'confirm_password_not_consistence':
      'Konfirmasi Kata Sandi tidak sama dengan with Kata Sandi',
  'phone': 'Nomor Telpon',
  'phone_placeholder': 'Masukan Nomor Telpon',
  'phone_is_required': 'Nomor Telpon harus diisi',
  'phone_min_max_validation': 'Masukan Nomor harus 6~15 karakter',
  'name': 'Nama',
  'name_placeholder': 'Masukan Nama',
  'name_is_required': 'Nama harus diisi',
  'name_min_max_validation': 'Nama harus 3~50 karakter',
  'privacy_policy': 'Kebijakan Pribadi',
  'aggree_with_term_policy':
      'Saya telah membaca dan menyetujui Syarat & Ketentuan dan Kebijakan Privasi dari Batix.',
  'home': 'Beranda',
  'sell': 'Penjualan',
  'buy': 'Pembelian',
  'me': 'Me',
  'setting': 'Seting',
  'inbox': 'Inbox',
  'change_password': 'Ubah Kata Sandi',
  'change_language': 'Ganti Bahasa',
  'change_theme': 'Ganti Tema',
  'contact': 'Kontak',
  'help': 'Bantuan',
  'about': 'Tentang',
  'more': 'Lihat Lainnya',
  'total_sell': 'Total Penjualan',
  'open_order': 'Open Order',
  'close_order': 'Close Order',
  'cash': 'Cash',
  'debit_card': 'Debit Card',
  'credit_card': 'Credit Card',
  'transfer': 'Transfer',
  'send_a_message': 'Kirim Pesan',
  'item': 'Barang',
  'properties': 'Properti',
  'billings': 'Tagihan',
  'transactions': 'Transaksi',
  'uncompletes': ' Data Belum Lengkap',
  'comercial': 'Komersial',
  'non_comercial': 'Non Komersial',
  'informal': 'PKL',
  'household': 'Rumah Tinggal',
  'transportation': 'Angkutan Umum',
  'social': 'Sosial',
  'public': 'Keramaian Umum',
  'open': 'Belum Bayar',
  'close': 'Sudah Bayar',
  'cancel': 'Dibatalkan',
  'amnesty': 'Pemutihan',
  'loginSuccess': 'Login Berhasil',
  'registerDevice': 'Pendaftaran Perangkat',
  'welcomeBack': 'Selamat Datang Kembali',
  'tryAgain': 'Coba lagi',
  'reset': 'Reset',
  'email': 'Email',
  'reset_password_alert':
      'Silahkan masukkan email anda untuk verifikasi akun anda.',
  'market-close': 'Pasar Libur',
  'booth-close': 'Kios Tutup',
  'booth-refuse': 'Kios Tidak Bayar',
};
